

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/comfy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: mysqlpw12!@
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true
          ddl-auto: create
      show-sql: true
      generate-ddl: true

  OAuth2:
      google:
        url: https://accounts.google.com/o/oauth2/v2/auth
        client-id: 150579669124-iuljf351licgh2lg7s35t1fcn9ct6k2h.apps.googleusercontent.com
        client-secret: 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
        callback-url: http://localhost:8080/auth/google/callback
        scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile

